// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnFarmCore.Repo;

namespace OnFarmCore.Repo.Migrations
{
    [DbContext(typeof(OnFarmContext))]
    partial class OnFarmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnFarmCore.Domain.Clientes", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_CLIENTE")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnName("BAIRRO")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Cep")
                        .HasColumnName("CEP")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Cidade")
                        .HasColumnName("CIDADE")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Complemento")
                        .HasColumnName("COMPLEMENTO")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("NmCliente")
                        .IsRequired()
                        .HasColumnName("NM_CLIENTE")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<int?>("Numero")
                        .HasColumnName("NUMERO");

                    b.Property<string>("Rua")
                        .HasColumnName("RUA")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Telefone")
                        .HasColumnName("TELEFONE")
                        .HasMaxLength(18)
                        .IsUnicode(false);

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("OnFarmCore.Domain.Pedidos", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PEDIDO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodRastreio")
                        .IsRequired()
                        .HasColumnName("COD_RASTREIO")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<DateTime?>("DtCriacao")
                        .HasColumnName("DT_CRIACAO")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdCliente")
                        .HasColumnName("ID_CLIENTE");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdCliente");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("OnFarmCore.Domain.Pedidos", b =>
                {
                    b.HasOne("OnFarmCore.Domain.Clientes", "IdClienteNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK__Pedidos__ID_CLIE__2A4B4B5E");
                });
#pragma warning restore 612, 618
        }
    }
}
